---
parameters:
  deployer_username: vagrant
  php:
    maxfilesize: '20M'
  memcached:
    ip: 127.0.0.1
    port: 11211
  apache:
    port: 81
  applications:
    - name:       devboard-notify
      template:   silex-application
      domain:     www.devboard-notify.loc
      path:       /var/www/sites/www.devboard-notify.loc
  mysql:
    ip: 127.0.0.1
    root_password: n0p455
  databases: []
  database_users: []
  git:
    rate_limit_token:   ADD-YOUR-OWN
  selenium:
    path:       /usr/lib/selenium
    log_path:   /var/log/selenium
    url:        http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar
    filename:   selenium-server-standalone-2.46.0.jar
  timezone: 'UTC'
